### ISSUE TITLE
ncurses flag missing for Makefile

### ISSUE THREAD

**Issue by Lang-Lovdog** [blippy/neoleo#50] opened 2024-12-16 08:27 UTC
I follow configure instructions after cloning repository,
`./conf #Runs successfully`
`./configure #Runs successfully`
`make # Error with curses lib dependencies`

```
/usr/bin/ld: io-2019.o: undefined reference to symbol 'delwin'
/usr/bin/ld: /lib64/libncursesw.so.6: error adding symbols: DSO missing from command line
```

I tried to solve it putting -lncurses in every '.*FLAGS' macro inside the generated Makefile but didn't work, but compiling copying and pasting the `g++ ...` command and adding the` -lncurses` given did work.

I use in Void Linux with kernel 6.6.65_1 if it's useful
Any other info I forget rn, let me know

**Comment by Lang-Lovdog** [comment] 2024-12-16 08:39
Editing `configure.ac` solved this, maybe it's due `pkg-config` not getting `ncurses` library data

**Comment by blippy** [comment] 2024-12-16 14:54
What is the result of typing:
```
pkg-config --libs ncurses
```
?

The problem is that adding "-lncurses" may not be sufficient on some platforms. For example, on Fedora:
```
$ pkg-config --libs ncurses
-lncurses -ltinfo
```

libtinfo might, or might not be (but often is) necessary. That's the advantage of using `pkg-config`. It sorts out those kinds of issues.

So I'm inclined to dig around and either make pkg-config a requirement in configure.ac, or else suggest build overrides. 

Otherwise, I run into the problem of what happens if -ltinfo is needed but it isn't specified, or contrariwise, if it is specified but doesn't exist.

**Update**: I think I may have found a good approach. Stay tuned. I will need you to check it out.

**Comment by blippy** [comment] 2024-12-16 16:22
Oops, I didn't mean to close the issue.

Could you please check compilation?

This may necessitate installing pkg-config on Void (or specifying your own flags), but I think this is likely to be the best approach.

**Comment by Lang-Lovdog** [comment] 2024-12-16 19:55
@blippy I ran `pkg-config --libs ncurses` and gives nothing, so I think it's a ncurses curse.
But, It seems that ncursesw is actually recognized by pkg-config, so I think it's something with `pkg-config` unable to find `ncurses-devel` data.

**Comment by blippy** [comment] 2024-12-16 20:26
Hmmm. Have you installed ncurses devel package? Try a simple program where you 
```
#include <ncurses.h>
```
to see if that works.

**Comment by blippy** [comment] 2024-12-16 20:33
If you're sure you've got everything installed, then try
```
./configure LDFLAGS="-lncurses"
```
or ncursesw, or some combination like that.

**Comment by Lang-Lovdog** [comment] 2024-12-16 21:06
@blippy, it seems that the variable is not working with conf nor configure.
``` bash
[lang_lovdog@theForest  15:03:03˙16:12,2024 neoleo] 󰩃 ./configure LDFLAGS="-lncurses"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: checking if debugging required ... no
configure: checking if gprof profiling required ... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ncurses... no
configure: error: Package requirements (ncurses) were not met:

No package 'ncurses' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NCURSES_CFLAGS
and NCURSES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

[lang_lovdog@theForest  15:03:14˙16:12,2024 neoleo] 󰩃 make
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
```
`make: *** No object was specified and no makefile was found. Stop.`

**Comment by blippy** [comment] 2024-12-16 23:46
You sure you've got the ncurses development libraries installed? What happens if you type
```
ls /usr/include/ncurses.h
```

**Comment by blippy** [comment] 2024-12-17 11:38
Aye carumba, what on earth is going on?

I did see an issue here:
https://github.com/void-linux/void-packages/pull/32988
"ncurses: install non-wide pkg-config files"

"Currently, there are symlinks to fool non-wide users into using the
proper .so/.a files, but pkg-config is unable to make use of them. This
installs the .pc files (which were already being generated)."

"this is intended, the non-widechar versions are not meant to be linked against and exist only for compatibility. software making bad assumptions at build time should be patched instead"

Hmm. This seems to suggest that the problem is with me, although I don't see why. If I tell it to link against ncurses, then that's what I expect to happen, and pkg-config should exist and link appropriately. 

In:
https://github.com/void-linux/void-packages/issues/32987
it says "not a bug". It seems that in Void Linux, ncurses library is linked against ncursesw, so there is a pkg-config for ncurses but not for ncursesw.

So
```
pkg-config --print-provides ncurses
```
produces no output (which oid claims is the correct behavior, but I disagree with), whilst
```
pkg-config --print-provides ncursesw
```
works as expected.

In effect, Void has broken a build which works on many other distros. 

Hmmm, I'll think about this and the best way forward.

**Comment by blippy** [comment] 2024-12-17 12:23
OK. I've decided to link against ncursesw instead of ncurses. Please test the latest commit 4fea2faa3d22dc47c2d50ff74d395dc9237d11fe and see if it now works. Thanks.

**Comment by Lang-Lovdog** [comment] 2024-12-17 15:35
@blippy With `ncursesw` it's solved. Compilation successfully finished!
Thanks!

**Closed as completed** 2024-12-18 18:51 UTC
